import React, { Component } from 'react'

// Graphql
import * as queries from '../graphql/queries';
import * as mutations from '../graphql/mutations';
import * as subscriptions from '../graphql/subscriptions';
// autogenerated graphQL query that retrieves all posts
import { listPosts } from '../graphql/queries'
import { API, graphqlQperation } from 'aws-amplify'

class DisplayPosts extends Component {

  componentDidMount = async () => {
    this.getPosts()
  }

  getPosts = async () => {
    const allPosts = await API.graphql({ query: queries.listPosts });
    console.log(`All Posts: ${JSON.stringify(allPosts.data.listPosts.items)}`);
    // const result = await API.graphql(graphqlQperation(queries.listPosts))
    // console.log("All post", JSON.stringify(result.data.listPosts.items));
    // See more at https://docs.amplify.aws/lib/graphqlapi/query-data/q/platform/js/#using-amplify-graphql-client
  }

  render() {
    return (
      <div>Hello World</div>
    )
  }
}

export default DisplayPosts